from io import BytesIO
import json
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from PIL import Image as PILImage

def generate_pdf_report(image_bytes: bytes, patient_data_json: str, prediction_json: str, advisory_json: str) -> bytes:
    patient_data = json.loads(patient_data_json) if patient_data_json else {}
    prediction = json.loads(prediction_json) if prediction_json else {}
    advisory = json.loads(advisory_json) if advisory_json else {}

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Center', alignment=1))
    
    Story = []

    # Title
    Story.append(Paragraph("<b>Melascope DX - Skin Lesion AI Assessment Report</b>", styles['Title']))
    Story.append(Spacer(1, 12))

    # Patient Context
    if patient_data:
        Story.append(Paragraph("<b>Patient Context</b>", styles['Heading2']))
        data = [
            ["Name", patient_data.get('name', 'N/A') or 'N/A'],
            ["Age", str(patient_data.get('age', 'N/A')) or 'N/A'],
            ["Gender", patient_data.get('gender', 'N/A') or 'N/A'],
            ["Location", patient_data.get('location', 'N/A') or 'N/A'],
            ["Symptoms", ", ".join(patient_data.get('symptoms', [])) if patient_data.get('symptoms') else 'None']
        ]
        t = Table(data, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
        ]))
        Story.append(t)
        Story.append(Spacer(1, 12))

    # Image
    if image_bytes:
        Story.append(Paragraph("<b>Analyzed Image</b>", styles['Heading2']))
        try:
            pil_img = PILImage.open(BytesIO(image_bytes))
            # Convert to RGB to avoid issues with some image formats in ReportLab
            if pil_img.mode != 'RGB':
                pil_img = pil_img.convert('RGB')
            pil_img.thumbnail((300, 300))
            img_io = BytesIO()
            pil_img.save(img_io, format='JPEG', quality=95)
            img_io.seek(0)
            
            rl_img = RLImage(img_io, width=4*inch, height=4*inch, kind='proportional')
            Story.append(rl_img)
            Story.append(Spacer(1, 12))
        except Exception as e:
            Story.append(Paragraph(f"[Image could not be rendered: {str(e)}]", styles['Normal']))

    # AI Prediction
    if prediction:
        Story.append(Paragraph("<b>AI Prediction</b>", styles['Heading2']))
        label = prediction.get('label', 'Unknown')
        conf = prediction.get('confidence', 0)
        Story.append(Paragraph(f"<b>Top Prediction:</b> {label} ({(conf*100):.1f}%)", styles['Normal']))
        Story.append(Spacer(1, 12))

    # Advisory
    if advisory:
        Story.append(Paragraph("<b>AI Advisory Insights</b>", styles['Heading2']))
        Story.append(Paragraph(f"<b>Title:</b> {advisory.get('title', '')}", styles['Normal']))
        Story.append(Spacer(1, 6))
        Story.append(Paragraph(f"<b>Summary:</b> {advisory.get('summary', '')}", styles['Normal']))
        Story.append(Spacer(1, 6))
        Story.append(Paragraph(f"<b>Next Steps:</b> {advisory.get('next_steps', '')}", styles['Normal']))
        Story.append(Spacer(1, 6))
        disclaimer = advisory.get('disclaimer', '')
        if disclaimer:
            Story.append(Paragraph(f"<i>Disclaimer: {disclaimer}</i>", styles['Italic']))
        Story.append(Spacer(1, 12))

    # Mandatory Footer/Disclaimer
    Story.append(Spacer(1, 24))
    Story.append(Paragraph("<i>Note: This document is generated by an AI assistant in Melascope DX. This is not a formal medical diagnosis. Always consult a licensed healthcare professional for medical advice, diagnosis, or treatment.</i>", styles['Italic']))

    doc.build(Story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
